name: Build
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project dependencies
        run: uv sync --locked --all-extras --dev

      # - name: Run tests
      #   run: uv run pytest

      - name: Build the project
        run: uv build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lgtm
          path: dist/

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*.whl
          tag_name: latest
          prerelease: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
