name: Build
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    environment: test-pypi
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest, windows-11-arm]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Python # might not be needed anymore
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install cibuildwheel
        run: uv tool install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp313-* cp314-*"
          CIBW_PRERELEASE_PYTHONS: "1"
          CIBW_BEFORE_ALL_LINUX: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
          CIBW_ENVIRONMENT_LINUX: PATH="$HOME/.cargo/bin:$PATH"
          MACOSX_DEPLOYMENT_TARGET: "14.0"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: lgtm-${{ matrix.os }}
          path: wheelhouse/

      - name: Publish to TestPyPI
        run: uv publish --index testpypi wheelhouse/*
